### PR TITLE
Load previous uploads

### LINKED ISSUE #58: Read previous uploads from localstorage
To show the list of previous uploads on the main page after a page reload we should read the list from localstorage. We may want to change the way items are stored so we don't need to iterate over all the keys.

### LINKED ISSUE #125: The "Delete" dialog is not dismissed when clicking the "Nevermind" button
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://p2p.dev.lcip.org/" page.
2. Upload a small file and click the "Send another file" button link.
3. Click the "x" button.
4. Click the "Nevermind" button and observe the behavior.

[Expected result]:
- The "Delete" dialog is dismissed.

[Actual results]:
- Nothing happens.

[Notes]:
- Click anywhere else on the dialog container will dismiss it.
- Clicking anywhere else on the page will not dismiss the dialog.
- This issue is also reproducible on the stage page (https://fileshare.stage.mozaws.net). 
- Here is a screen recording with the issue:
nevermind

### PR DESCRIPTION
**Pull request by dnarcese**
-shows previous uploads on refresh
-fix Nevermind button

Fixes #58 
Fixes #125

### CODE REVIEW

File: frontend/src/upload.js [hunk 1]
```diff
@@ -11,13 +11,18 @@ $(document).ready(function() {
...
 
+  for (let i = 0; i < localStorage.length; i++) {
+    let id = localStorage.key(i);
+    populateFileList(localStorage.getItem(id));
+  }
+
   // copy link to clipboard
   $copyBtn.click(() => {
-    const aux = document.createElement('input');
+    var aux = document.createElement('input');
```
Comment (ericawright) [inline frontend/src/upload.js]: use 'let'
